# -*- coding: utf-8 -*-
"""ODS14_RLS_MA1053.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Gv3N2XzyVeT9TC5-IA62V3bSzfEIhJbT

# Proyecto: Inteligencia Artificial para Energía Sostenible (ODS 7)Modelo de Predicción de Producción de Energía Eólica mediante Regresión Lineal

**Introducción al Problema:** El Poder del Viento
La energía eólica es una de las fuentes más importantes de energía limpia en el mundo. Aprovecha la fuerza del viento para generar electricidad sin emitir gases contaminantes.
Sin embargo, uno de los principales retos es su variabilidad.
¿Qué sucede?
La cantidad de energía generada depende de factores como la velocidad del viento, condiciones climáticas y ubicación geográfica.

**Consecuencia:**
Si no se predice correctamente la producción, puede haber desperdicio de energía, fallas en el suministro y mala planificación energética.
El Rol de la Ingeniería y los Datos
En el marco del ODS 7, el uso de datos y Machine Learning permite:
Predecir cuánta energía se generará.
Optimizar el uso de recursos energéticos.
Mejorar la estabilidad del suministro eléctrico.
Reducir la dependencia de energías no renovables.
Objetivos del Notebook
En esta sesión cubriremos el flujo completo de un proyecto de ciencia de datos:

**Carga de Datos:** Uso de Pandas para analizar el dataset de energía eólica.

**Limpieza:** Tratamiento de valores nulos o inconsistentes.

**Análisis:** Exploración de la relación entre variables (ej. viento y producción).

**Modelado:** Creación de un modelo de regresión lineal.

**Evaluación:** Validación del desempeño del modelo.

**Despliegue:** Preparación para una app interactiva en Streamlit.

**Definición del Dataset**

Trabajaremos con el archivo Energia_eolica_ODS7.csv, que contiene registros de producción energética.

**Variable independiente (X):** Velocidad_Viento (intensidad del viento)
**Variable objetivo (y):** Produccion_kWh (energía generada)

# **Fase 1: Carga y Exploración (Pandas)**
"""

import pandas as pd
import numpy as np
import streamlit as st

df = pd.read_csv('ene2.csv')
df

print("--- Primeros registros del Dataset ---\n")
print(df.head())

#Inspección
print("\n--- Resumen de la estructura de datos ---\n")
df.info()

"""# **Fase 2: Limpieza de Datos**"""

# Detección de valores nulos
print("--- Cantidad de datos faltantes por columna ---\n")
print(df.isnull().sum())

# Limpieza: Eliminación de valores vacíos
df = df.dropna()

# Reiniciamos el índice
df = df.reset_index(drop=True)

# Revisamos nuevamente el número de valores nulos
print("--- Cantidad de datos faltantes por columna ---\n")
print(df.isnull().sum())

# Nuevo tamaño del dataset
print("--- Dimensiones del dataset ---\n")
df.shape

df

#Sirve para crear un nuevo archivo csv
df.to_csv('ene2.csv', index=False)

"""# **Fase 3: Ingeniería de Características**"""

# Visualización de la relación entre las variables y te lo grafica
plt.scatter(df['Velocidad_Viento_ms'], df['Eficiencia_Energetica_kWh'])
plt.title('Relación: Velocidad del viento y la eficiencia energética')
plt.xlabel('Velocidad del viento') #etiqueta
plt.ylabel('eficiencia energetica kwh') #etiqueta
plt.grid(True, linestyle='--')
plt.show() #Sirve para mostrar la grafica

# Selección de variables

# X es la variable independiente
X = df[['Velocidad_Viento_ms']]
#  y es la variable objetivo
y = df['Eficiencia_Energetica_kWh']

# División de datos (Entrenamiento y prueba)

# Importamos la librería para la separación
from sklearn.model_selection import train_test_split

# Reservamos el 30% de los datos para probar el modelo al final

### -----> CAMBIAR en random_state=0 el 0 por su número de MATRÍCULA
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.30, random_state=1068493)

"""# **Fase 4: Entrenamiento del Modelo (Scikit-Learn)**"""

# Importamos la librería para la regresión lineal
from sklearn.linear_model import LinearRegression

# Creación del Modelo
LR = LinearRegression()

# Entrenamiento del Modelo le damos los datos para que pueda aprender
LR.fit(X_train, y_train)

# Verificamos el ajuste a los datos de entrenamiento tratar de que se acerque a 1 para que su predicción sea más asertada
LR.score(X_train, y_train)

"""Cálculo de los coeficientes de la ecuación de regresión lineal"""

# Pendiente de la recta
b1 = LR.coef_
print("Pendiente de la recta \n m =", b1)

# Intersección con el eje y
b0 = LR.intercept_
print("Intersección con el eje y \n b =", b0)

"""# **Fase 5: Validación y Predicción**"""

# Importamos la librería para la métrica r^2
from sklearn.metrics import r2_score

# Cálculo de r^2
# Una puntuación de 1 indica un ajuste perfecto
# Una puntuación de 0 indica que el modelo no es apto para predecir la variable objetivo

#Tiene que ser muy parecido al LR. Score de entrenamiento

r2 = LR.score(X_test, y_test)
print("R^2 score =", r2)

# Visualización del Modelo Resultante
pred = LR.predict(X_test)
plt.scatter(X, y, label='Datos reales')
plt.plot(X_test, pred, color='yellow', linewidth=2, label='Línea de Regresión')
plt.title('Modelo de Predicción de energía ')
plt.xlabel('Velocidad del viento')
plt.ylabel('Eficiencia energetica')
plt.legend()
plt.show()

"""# **Fase 6: Hacia el Despliegue (Streamlit)**

El objetivo de Streamlit es permitir que cualquier persona (un biólogo marino, un político o un ciudadano) use nuestro modelo de IA sin necesidad de saber programar.
"""

# Commented out IPython magic to ensure Python compatibility.
# #Se cambia en cada trabajo para crear un nuevo archivo de pyton
# %%writefile Corales.py
# # Importar librerías necearias
# import numpy as np
# import streamlit as st
# import pandas as pd
# 
# # Insertamos título
# st.write(''' # ODS 7: Energía Asequible y No Contaminante''')
# # Insertamos texto con formato
# st.markdown("""
# Esta aplicación utiliza **Machine Learning** para predecir el impacto del nivel del viento en la generación de energía **ODS 7: Energía Asequible y No Contaminante**.
# """)
# # Insertamos una imagen
# st.image("enes.jpg", caption="Eficiencia energética de acuerdo al nivel del viento.")
# 
# 
# # Definimos cómo ingresará los datos el usuario
# # Usaremos un deslizador
# st.sidebar.header("Velocidad del viento")
# # Definimos los parámetros de nuestro deslizador:
#   # Límite inferior: 24°C. Es el límite inferior donde los arrecifes tropicales suelen estar cómodos
#   # Límite superior: 35°C. La mayoría de los corales mueren o se blanquean totalmente mucho antes de llegar a esa temperatura
#   # Valor inicial: 28°C. En muchos arrecifes, a partir de los 28.5°C o 29°C comienza el estrés térmico severo
# temp_input = st.sidebar.slider("Velocidad del viento en m/s",0,30)
# 
# # Cargamos el archivo con los datos (.csv)
# df =  pd.read_csv('ene2.csv', encoding='latin-1')
# # Seleccionamos las variables
# X = df[['Velocidad_Viento_ms']]
# y = df['Eficiencia_Energetica_kWh']
# 
# # Creamos y entrenamos el modelo
# from sklearn.model_selection import train_test_split
# from sklearn.linear_model import LinearRegression
# X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.30, random_state=0)
# LR = LinearRegression()
# LR.fit(X_train,y_train)
# 
# # Hacemos la predicción con el modelo y la temperatura seleccionada por el usuario
# b1 = LR.coef_
# b0 = LR.intercept_
# prediccion = b0 + b1[0]*temp_input
# 
# # Presentamos loa resultados
# st.subheader('Eficiencia energetica')
# st.write(f'El nivel de energía es: {prediccion:.2f} Wkh')
# 
# if prediccion < 500:
#         st.success("Eficiencia baja")
# elif prediccion < 3000:
#         st.warning("Alta eficiencia")
# else:
#         st.error("Muy alta eficiencia")
